### ISSUE TITLE
when you will finish usage documentation?

### ISSUE THREAD

**Issue by AbdullahGhanem** [ARCANEDEV/SEO-Helper#1]

**Comment by arcanedev-maroc** [comment]
السلام عليكم

The API still **Work In Progress** phase, but i'm working on it.

> You can take a look at the source code and especially at the `Contracts` folder.

Stay tuned :+1:

**Comment by AbdullahGhanem** [comment]
وعليكم السلام اخي :+1: 
شكرا

**Comment by arcanedev-maroc** [comment]
You're welcome bro :wink:.

**Comment by arcanedev-maroc** [comment]
By the way, you can also check the `tests` folder (i totally forget about that :laughing:), it's a great place to start with.

It contains many examples and how to use this package (API).

**Comment by AbdullahGhanem** [comment]
thanks
