### ISSUE TITLE
blade usage

### ISSUE THREAD

**Issue by mkibach** [ARCANEDEV/SEO-Helper#10]
hello,
how to output result into blade.

I put this lines into my controller :

``` php
$title = new Title;
$title->set('Your awesome title');
echo $title->render();
```

this render the title before head tag, I need to set the title inside head to respect html strecture

can you help please ?

**Comment by arcanedev-maroc** [comment]
You can use the `seo_helper()` helper to achieve this.

In your Controller :

``` php
public function index()
{
    seo_helper()->setTitle('Your awesome title');

    return view('your-index-view');
}
```

In your view (or master view):

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    {!! seo_helper()->render() !!}
</head>
<body>
    <!-- Your content -->
</body>
</html>
```

**Comment by mkibach** [comment]
hello,
Thank you for your answer, your suggestion work fine for :

``` php
seo_helper()->setTitle('xxxxx');
seo_helper()->setDescription('yyyyy');
seo_helper()->setKeywords($keywords);
```

but not for :

``` php
seo_helper()->setSeoOpenGraph($openGraph);
seo_helper()->setSeoTwitter($seoTwitter);
```

I have created a seoTwiter instance of Card this way

``` php
$seoTwitter = new Card([
    'prefix' => 'twitter:',
    'card' => 'summary',
    'site' => '@ttttt',
    'metas' => [
        'creator' => '@ttttt',
        'url' => 'http://www.url.com',
        'image' => 'http://url.com/img/logo.png',
    ],
]);
```

I got this exception :
`ErrorException in SeoHelper.php line 138: Argument 1 passed to Arcanedev\SeoHelper\SeoHelper::setSeoTwitter() must implement interface Arcanedev\SeoHelper\Contracts\SeoTwitter, instance of Arcanedev\SeoHelper\Entities\Twitter\Card given, called in C:\lv-project\app\Http\Controllers\ContactController.php on line 48 and defined`

**Comment by arcanedev-maroc** [comment]
**Note :** The `Arcanedev\SeoHelper\SeoTwitter` is the manager class to manage twitter tags (implements the `Arcanedev\SeoHelper\Contracts\SeoTwitter` interface) and the `Arcanedev\SeoHelper\Entities\Twitter\Card` is the card entity for twitter, same thing for opengraph.

So the correct way is to add the entity to the manager, like this:

``` php
use Arcanedev\SeoHelper\Entities\Twitter\Card;

$twitterCard = new Card([
    'prefix' => 'twitter:',
    'card' => 'summary',
    'site' => '@ttttt',
    'metas' => [
        'creator' => '@ttttt',
        'url' => 'http://www.url.com',
        'image' => 'http://url.com/img/logo.png',
    ],
]);

seo_helper()->twitter()->setCard($twitterCard);
```

**Comment by mkibach** [comment]
Thank you.
