### ISSUE TITLE
How to disable html encode?

### ISSUE THREAD

**Issue by pe3udent** [ARCANEDEV/SEO-Helper#24]
- SEO-Helper Version: 1.2.1
- Laravel Version: 5.2.45
- PHP Version: 7.0.8

Hi,
How to disable html encode in setDescription()?

`«description» -> &laquo;description&raquo;`

Thanks

**Comment by arcanedev-maroc** [comment]
This feature does not exist for the time being, all the content are escaped to avoid conflicts.

Feel free to add this feature by making a PR 👍
