### ISSUE TITLE
get only title string

### ISSUE THREAD

**Issue by Themesfa** [ARCANEDEV/SEO-Helper#37]
hi . i want to get site title and use in other place on page layout .
how i should get title string without meta html ?

**Comment by arcanedev-maroc** [comment]
What's the output you're getting ?

Or you want to do something like this ? 
```blade
<h1>{{ seo_helper()->meta()->getTitle() }}</h1>
```

**Comment by Themesfa** [comment]
my codes : 

**UserController.php**
```php
public function show() 
{
    $this->seo()->setTitle('Users','Themesfa','&lsaquo;');

    return view( 'users' );
}
```
**users.blade.php**
```blade
<head>
    {!! seo_helper()->render() !!}
</head>
<body>
    ...
    ...
    <div class="page-header"><h1>"I want to print page title here"</h1></div>
</body>
```

the output in head is => <title>Users &lsaquo; Themesfa</title>
and its ok . but i want to use title in h1 tag again. how i can do it ? 
i cant find any method to help me in this case .

**Comment by arcanedev-maroc** [comment]
There is a workaround for this:

**UserController.php**
```php
public function show() 
{
    $this->seo()->setTitle($title = 'Users','Themesfa','&lsaquo;');

    return view('users', compact('title'));
}
```
**users.blade.php**
```blade
<head>
    {{ seo_helper()->renderHtml() }}
</head>
<body>
    ...
    ...
    <div class="page-header"><h1>{{ $title or 'Default title' }}</h1></div>
</body>
```

I'm going to think about this feature if doesn't exists 👍

**Comment by Themesfa** [comment]
it works, but Have any idea how to make it more beautiful?
i think you must create a method and return all seo Variables  . so users can access seo Variables in blade.

**Comment by arcanedev-maroc** [comment]
In my projects, i always extend my base controller to make things **beautiful** and *organized*, something like this:

**Controller.php** *(using Arcanedev\SeoHelper\Traits\Seoable)*

```php
public function setTitle($title, $siteName = null, $separator = null)
{
    view()->share('title', $title);

    return parent::setTitle($title, $siteName, $separator);
}
```

**UserController.php**
```php
public function show()
{
    $this->setTitle('Users','Themesfa','&lsaquo;');

    return view('users');
}
```
**users.blade.php**
```blade
<head>
    {{ seo_helper()->renderHtml() }}
</head>
<body>
    ...
    ...
    <div class="page-header"><h1>{{ $title or 'Default title' }}</h1></div>
</body>
```

**Comment by Themesfa** [comment]
you right👍 . i'm new in laravel . forgive me
thank you for your help.

**Comment by arcanedev-maroc** [comment]
PR: #38

Now you can access the title entity with: `seo_helper()->meta()->getTitleEntity()->getTitleOnly()`
