### ISSUE TITLE
Extend Laravel support for custom meta and link tags

### ISSUE THREAD

**Issue by bridgeport** [ARCANEDEV/SEO-Helper#40]
- SEO-Helper Version: 1.5.1
- Laravel Version: 5.6.5
- PHP Version: 7.1.14

### Description:

Thanks for this package. Do you have any plans to extend the Laravel Trait to support the full range of capabilities this package has, such as being able to do the following:
```php
class PostController extends Controller
{
    public function list()
    {
        $this->seo()->addMeta('prev', url('/page-1')); // Or 'addLink()' if more appropriate.
        $this->seo()->addMeta('next', url('/page-3'));
        $this->seo()->addMeta('robots', 'follow, noindex');
    }
}
```

**Comment by arcanedev-maroc** [comment]
You can do this:

```php
$this->seo()->meta()->addMeta('prev', url('/page-1'));
$this->seo()->meta()->addMeta('next', url('/page-3'));
$this->seo()->meta()->addMeta('robots', 'follow, noindex');

// OR
$this->seo()->meta()->addMeta('prev', url('/page-1'))
                    ->addMeta('next', url('/page-3'))
                    ->addMeta('robots', 'follow, noindex');

// OR
$this->seo()->meta()->addMetas([
    'prev'   => url('/page-1'),
    'next'   => url('/page-3'),
    'robots' => 'follow, noindex',
]);
```

For the `addLink()`, you can make a PR to add this feature in the `SeoMeta` class if you want.

Hope this helps you :+1:

**Comment by bridgeport** [comment]
@arcanedev-maroc Thanks for pointing this out. It's exactly what I need.

I see there's no need for `addLink()` as your package already properly maps properties like `prev` and `next` to render with the link tag instead of meta tag.

Thanks again.
