### ISSUE TITLE
How to implement hreflang for language and regional URLs

### ISSUE THREAD

**Issue by SpinyMan** [ARCANEDEV/SEO-Helper#41]
- SEO-Helper Version: 1.4
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
I've got a multi-language website & google propose use alternate meta tags instead of canonical. Here the article is:
[Use hreflang for language and regional URLs](https://support.google.com/webmasters/answer/189077?hl=en)
So, the question is how to implement this feature via seo-helper?

**Comment by arcanedev-maroc** [comment]
This feature is not available but you can make a PR to add it.

You can start with an Entity class, something like `LinkTag` Class.
