### ISSUE TITLE
is your aswome package have Database support?

### ISSUE THREAD

**Issue by iozeey** [ARCANEDEV/SEO-Helper#6]

**Comment by arcanedev-maroc** [comment]
No, but you can use your own database.

**Comment by iozeey** [comment]
can you suggest any package that have both in one?

**Comment by arcanedev-maroc** [comment]
As you can see, this repo is a framework agnostic package (works with any PHP project).

If you want a seo package for laravel, try to search here : http://packalyst.com/s/seo
