### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by abishekrsrikaanth** [ARCANEDEV/SEO-Helper#61]
Can you please add support for Laravel 10

**Comment by colivinggit** [comment]
Please help to update the package to support Laravel 10...

**Comment by matthewheck17** [comment]
Will Laravel 10 be supported anytime soon?

**Comment by colivinggit** [comment]
We moved to archtechx/laravel-seo instead.
Easy transition: They update their package straight after each new Laravel version.

**Comment by matthewheck17** [comment]
awesome thanks i will look into that!
